### ISSUE TITLE
Database may not be created due to incorrect path given

### ISSUE THREAD

**Issue by hldup** [TGyAkos/todoApp#1]
https://github.com/TGyAkos/todoApp/blob/26540b14ccb054a8f03f67660c3087df413e6cc5/src/task_orm.py#L12

# Steps to reproduce
- Run app from directory with no upper path to it and with no root permissions

`sqlite3.OperationalError: unable to open database file`

**Comment by TGyAkos** [comment]
it has been fixed i think
